# https://realpython.com/flask-connexion-rest-api/#getting-started
swagger: "2.0"
info:
  description: This defines the API for panel_gen
  version: "1.0.0"
  title: panel_gen traffic generator
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /switch:
    get:
      operationId: switch.read_all
      tags:
        - switch
      summary: Read all switch objects
      description: Read all switch objects
      responses:
        200:
          description: Successful read switch operation
          schema:
            type: array
            items:
              properties:
                kind:
                  type: string
                running:
                  type: boolean
                max_calls:
                  type: integer
                max_dialing:
                  type: integer
                is_dialing:
                  type: integer 
                dahdi_group:
                  type: string
                nxx:
                  type: array
                line_range:
                  type: array
                trunk_load:
                  type: array

  /switch/{kind}:
    get:
      operationId: switch.read_one
      tags:
      - switch
      summary: Read one switch from the switches list
      description: Read one switch from the switches list
      parameters:
      - name: kind
        in: path
        description: Kind of switch to get from the list
        type: string
        required: True
      responses:
        200:
          description: Successfully read switch from switches list operation
          schema:
            properties:
              kind:
                type: string
              running:
                type: boolean
              max_calls:
                type: integer
              max_dialing:
                type: integer
              is_dialing:
                type: integer
              dahdi_group:
                type: string
              nxx:
                type: array
              line_range:
                type: array
              trunk_load:
                type: array

    post:
        operationId: switch.create
        tags:
          - switch
        summary: Create a new instance of a switch
        description: Instantiate a switch object
        parameters:
          - name: kind
            in: path
            description: Virtual switch to create
            type: string
            required: True
#            schema:
#              type: array
#              properties:
#                kind:
#                  type: string
#                  description: Type of switch to create
#                 running:
#                 type: boolean
#                 description: Whether or not the switch is actively processing calls
#               max_calls:
#                  type: integer
#                  description: Number of currently active lines
#                max_dialing:
#                  type: integer
#                  description: Maximum number of calls that may be dialing at one time
#                is_dialing:
#                  type: integer
#                  description: Number of lines on switch that are currently dialing
#                dahdi_group:
#                  type: string
#                  description: DAHDI group to place calls on. Normally not needed
#                nxx:
#                  type: string
#                  description: List of office codes we can dial from this switch 
#                line_range:
#                  type: string
#                  description: Range of lines we can dial to this switch
        responses:
          201:
            description: Successfully created switch

    patch:
      operationId: switch.update
      tags:
        - switch
      summary: Update a switch in the switches list
      description: Update a switch in the switches list
      parameters:
        - name: kind
          in: path
          description: Kind of switch to update in the list
          type: string
          required: True
        - name: switch
          in: body
          schema:
            type: object
            properties:
              running:
                type: boolean
              max_calls:
                type: integer
              max_dialing:
                type: integer
              dahdi_group:
                type: string
              nxx:
                type: array
              line_range:
                type: array
              trunk_load:
                type: array
      responses:
        200:
          description: Successfully updated switch in switches list

    delete:
      operationId: switch.delete
      tags:
        - switch
      summary: Delete a switch from the switches list
      description: Delete a switch
      parameters:
        - name: kind
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a switch from switches list

  /line:
    get:
      operationId: line.read_all
      tags:
        - line
      summary: Read all line objects
      description: Read all line objects
      responses:
        200:
          description: Successful read line operation
          schema:
            type: array
            items:
              properties:
                switch:
                  type: string
                timer:
                  type: integer
                hook_state:
                  type: integer
                ast_status:
                  type: string
                dahdi_chan:
                  type: integer 
                calling_no:
                  type: string

    post:
        operationId: line.create
        tags:
          - line
        summary: Create a new instance of a line
        description: Instantiate a line object
        parameters:
          - name: line
            in: body
            description: Virtual linee to create
            required: True
            schema:
              type: object
              properties:
                switch:
                  type: string
                  description: Switch this line will call from
                timer:
                  type: integer
                  description: Number of seconds remaining until next action
                hook_state:
                  type: integer
                  description: 0 = On hook / 1 = Off hook
                ast_status:
                  type: string
                  description: Status of the line in Asterisk
                is_dialing:
                  type: boolean
                  description: Whether or not the line is currently holding a sender
                dahdi_chan:
                  type: integer
                  description: DAHDI channel the line belongs to
                calling_no:
                  type: string
                  description: Number the line will call
        responses:
          201:
            description: Successfully created line

  /line/{key}:
    get:
      operationId: line.read_one
      tags:
      - line
      summary: Read one line from the lines list
      description: Read one line from the lines list
      parameters:
      - name: key
        in: path
        description: Key of line to get from the list
        type: string
        required: True
      responses:
        200:
          description: Successfully read line from lines list operation
          schema:
            properties:
              switch:
                type: string
              timer:
                type: integer
              hook_state:
                type: integer
              ast_status:
                type: string
              is_dialing:
                type: boolean
              dahdi_chan:
                type: integer
              calling_no:
                type: string
    patch:
      operationId: line.update
      tags:
        - line
      summary: Update a line in the lines list
      description: Update a line in the lines list
      parameters:
        - name: key
          in: path
          description: Key of line to update in the list
          type: string
          required: True
        - name: line
          in: body
          schema:
            type: object
            properties:
              switch:
                type: string
              timer:
                type: integer
              hook_state:
                type: integer
              ast_status:
                type: string
              is_dialing:
                type: boolean
              dahdi_chan:
                type: integer
              calling_no:
                type: string
      responses:
        200:
          description: Successfully updated line in lines list

    delete:
      operationId: line.delete
      tags:
        - line
      summary: Delete a line from the lines list
      description: Delete a line
      parameters:
        - name: key
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully deleted a line from lines list

  /app:
    get:
      operationId: app.read_status
      tags:
        - app
      summary: Get general app status information
      description: Gets high-level app status
      responses:
        200:
          description: Successful app read operation
          schema:
            type: string
            items:
              properties:
                running:
                  type: boolean

  /app/operate:
    post:
      operationId: app.operate
      tags:
        - app
      summary: Start execution of the work thread. 
      description: Starts all existing switches. Name is a joke on Bell System terminology.

      responses:
        201:
          description: Successfully started work thread

  /app/nonoperate:
    post:
      operationId: app.nonoperate
      tags:
        - app
      summary: Stop execution of the work thread.
      description: Stop all actions and release lines. Another Bell System in-joke.

      responses:
        201:
          description: Successfully killed app

  /app/paused:
    post:
      operationId: app.api_pause
      tags:
        - app
      summary: Pause execution but leave app running to unpause later.
      description: Pause app but leave things in a resumable state.

      responses:
        201:
          description: Successfully paused work thread

  /app/resumed:
    post:
      operationId: app.api_resume
      tags:
        - app
      summary: Resume from paused state. Picks up where it left off.
      description: Resume from last state.

      responses:
        201:
          description: Successfully resumed work thread
