# https://realpython.com/flask-connexion-rest-api/#getting-started
swagger: "2.0"
info:
  description: This defines the API for panel_gen
  version: "1.0.0"
  title: panel_gen traffic generator
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /app:
    get:
      operationId: app.read_status
      tags:
        - app
      summary: Get general app status information
      description: Gets high-level app status
      responses:
        200:
          description: Successful app read operation
          schema:
            type: string
            items:
              properties:
                running:
                  type: boolean

  /app/start/{switch}:
    post:
      operationId: app.start
      tags:
        - app
      summary: Start calls on a switch.
      description: Starts calls on a particular switch.
      parameters:
        - name: switch
          in: path
          description: Switch to originate call from
          type: string
          required: True
        - name: mode
          in: query
          description: Allows starting demo mode
          type: string
        - name: source
          in: query
          description: Changes response to 303 when running from web page.
          type: string

      responses:
        201:
          description: Successfully started processing calls on switch.
        303:
          description: Successfully started with redirect to home page.
        406:
          description: Failed to start calls on switch.

  /app/stop/{switch}:
    post:
      operationId: app.stop
      tags:
        - app
      summary: Stop calls on a switch..
      description: Stop all actions and release lines. Use /stop/all to stop everything.
      parameters:
        - name: switch
          in: path
          description: Switch to stop. 'all' for all switches.
          type: string
          required: True
        - name: source
          in: query
          description: Changes response to 303 when running from web page.
          type: string

      responses:
        201:
          description: Successfully stopped processing calls.
        303:
          description: Successfully stopped with redirect to home page.
        406:
          description: Failed to stop calls on switch.


#  /app/pause:
#    post:
#      operationId: app.api_pause
#      tags:
#        - app
#      summary: Pause execution but leave app running to unpause later.         
#      description: Pause app but leave things in a resumable state.

#      responses:
#        201:
#          description: Successfully paused work thread

#  /app/resume:
#    post:
#      operationId: app.api_resume
#      tags:
#        - app
#      summary: Resume from paused state. Picks up where it left off.
#      description: Resume from last state.

#      responses:
#        201:
#          description: Successfully resumed work thread

  /call/{switch}/{destination}:
    post:
      operationId: app.call
      tags:
        - app
      summary: Place a call now.
      description: Place a call immediately.
      parameters:
        - name: switch
          in: path
          description: Switch to originate call from
          type: string
          required: True
        - name: destination
          in: path
          description: Destination line to call
          type: string
          required: True

      responses:
        200:
          description: Successfully placed call

  /switches:
    get:
      operationId: switches.read_all
      tags:
        - switches
      summary: Read all switch objects
      description: Read current status of all switches
      responses:
        200:
          description: Successful read switch operation
          schema:
            type: array
            items:
              properties:
                kind:
                  type: string
                running:
                  type: boolean
                max_calls:
                  type: integer
                max_dialing:
                  type: integer
                is_dialing:
                  type: integer 
                dahdi_group:
                  type: string
                nxx:
                  type: array
                line_range:
                  type: array
                trunk_load:
                  type: array

  /switches/{kind}:
    get:
      operationId: switches.read_one
      tags:
      - switches
      summary: Read one switch from the switches list
      description: Read current status of a particular switch
      parameters:
      - name: kind
        in: path
        description: Kind of switch to get from the list
        type: string
        required: True
      responses:
        200:
          description: Successfully read switch from switches list operation
          schema:
            properties:
              kind:
                type: string
              running:
                type: boolean
              max_calls:
                type: integer
              max_dialing:
                type: integer
              is_dialing:
                type: integer
              dahdi_group:
                type: string
              nxx:
                type: array
              line_range:
                type: array
              trunk_load:
                type: array
              traffic_load:
                type: string

    post:
        operationId: switches.create
        tags:
          - switches
        summary: Create a new instance of a switch
        description: Instantiate a switch object
        parameters:
          - name: kind
            in: path
            description: Virtual switch to create
            type: string
            required: True
#            schema:
#              type: array
#              properties:
#                kind:
#                  type: string
#                  description: Type of switch to create
#                 running:
#                 type: boolean
#                 description: Whether or not the switch is actively processing calls
#               max_calls:
#                  type: integer
#                  description: Number of currently active lines
#                max_dialing:
#                  type: integer
#                  description: Maximum number of calls that may be dialing at one time
#                is_dialing:
#                  type: integer
#                  description: Number of lines on switch that are currently dialing
#                dahdi_group:
#                  type: string
#                  description: DAHDI group to place calls on. Normally not needed
#                nxx:
#                  type: string
#                  description: List of office codes we can dial from this switch 
#                line_range:
#                  type: string
#                  description: Range of lines we can dial to this switch
        responses:
          201:
            description: Successfully created switch

    patch:
      operationId: switches.update
      tags:
        - switches
      summary: Update a switch in the switches list
      description: Update an already existing switch in the switches list
      parameters:
        - name: kind
          in: path
          description: Kind of switch to update in the list
          type: string
          required: True
        - name: switch
          in: body
          schema:
            type: object
            properties:
              running:
                type: boolean
              max_calls:
                type: integer
              max_dialing:
                type: integer
              dahdi_group:
                type: string
              nxx:
                type: array
              line_range:
                type: array
              trunk_load:
                type: array
              traffic_load:
                type: string
      responses:
        200:
          description: Successfully updated switch in switches list

  /lines:
    get:
      operationId: lines.read_all
      tags:
        - lines
      summary: Represents line objects
      description: Read all lines
      responses:
        200:
          description: Successful read line operation
          schema:
            type: array
            items:
              properties:
                ident:
                  type: string
                switch:
                  type: string
                timer:
                  type: integer
                hook_state:
                  type: integer
                ast_status:
                  type: string
                dahdi_chan:
                  type: string
                called_no:
                  type: string

    delete:
      operationId: lines.delete_all
      tags:
        - lines
      summary: Represents line objects
      description: Deletes all lines
      responses:
        204:
          description: Successful delete line operation

  /lines/{ident}:
    get:
      operationId: lines.read_one
      tags:
      - lines
      summary: Read one line from the lines list
      description: Read one line from the lines list
      parameters:
      - name: ident
        in: path
        description: Key of line to get from the list
        type: string
        required: True
      responses:
        200:
          description: Successfully read line from lines list operation
          schema:
            properties:
              ident:
                type: string
              switch:
                type: string
              timer:
                type: integer
              hook_state:
                type: integer
              ast_status:
                type: string
              is_dialing:
                type: boolean
              dahdi_chan:
                type: string
              called_no:
                type: string
    patch:
      operationId: lines.update
      tags:
        - lines
      summary: Update a line in the lines list
      description: Update an already existing line in the lines list
      parameters:
        - name: ident
          in: path
          description: Identity of line to update in the list. Normally an integer, starting at 0
          type: string
          required: True
        - name: line
          in: body
          schema:
            type: object
            properties:
              switch:
                type: string
              timer:
                type: integer
              hook_state:
                type: integer
              ast_status:
                type: string
              is_dialing:
                type: boolean
              dahdi_chan:
                type: string
              called_no:
                type: string
      responses:
        200:
          description: Successfully updated line

    delete:
      operationId: lines.delete
      tags:
        - lines
      summary: Delete a line from the lines list
      description: Delete a line
      parameters:
        - name: ident
          in: path
          type: string
          required: True
      responses:
        204:
          description: Successfully deleted a line

  /lines/{switch}:
    post:
        operationId: lines.create
        tags:
          - lines
        summary: Create a new line
        description: Instantiate a line object belonging to a particular switch.
        parameters:
          - name: switch
            in: path
            description: Switch that the line will originate from
            type: string
            required: True
#            schema:
#              type: object
#              properties:
#                ident: 
#                  type: string
#                  description: Number of this line in list.
#                switch:
#                  type: string
#                  description: Switch this line will call from
#                timer:
#                  type: integer
#                  description: Number of seconds remaining until next action
#                hook_state:
#                  type: integer
#                  description: 0 = On hook / 1 = Off hook
#                ast_status:
#                  type: string
#                  description: Status of the line in Asterisk
#                is_dialing:
#                  type: boolean
#                  description: Whether or not the line is currently holding a sender
#                dahdi_chan:
#                  type: integer
#                  description: DAHDI channel the line belongs to
#                called_no:
#                  type: string
#                  description: Number the line will call
        responses:
          201:
            description: Successfully created line
